[package]
name = "clinewsapp"
version = "0.1.0"
edition = "2021"

[dependencies]

colour = "2.1.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.64"
ureq = "2.6.1"
